project:
  title: "2024_unibe_protocol"

website:
  title: "Why we need protocols in research"
  navbar:
    left:
      - href: index.qmd
        text: Presentation

format:
  html:
    theme: cosmo
    toc: false

